# Generated by Django 4.2.4 on 2023-08-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreoia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
